routes/web.php
<?php

use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FunctionsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotifyController;
use App\Jobs\EmailTo;
use App\Mail\NotifyUser;
use App\Models\Notify;
use App\Models\User;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('index');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/language/{lang}', [FunctionsController::class, 'language'])->name('language');

Route::get('/about', [HomeController::class, 'about'])->name('about');

Route::get('/info-platform', [HomeController::class, 'vacancies'])->name('vacancies');

Route::get('/contact', [HomeController::class, 'contact'])->name('contact');

Route::group(['prefix' => 'admin', 'middleware' => ['isAdmin']], function () {
    Route::get('/', [AdminDashboardController::class, 'index'])->name('admin');
    Route::get('/message', [AdminDashboardController::class, 'message'])->name('admin.message');
    Route::post('/message/changeStatus/{id}', [AdminDashboardController::class, 'messageChangeStatus'])->name('admin.message.changeStatus');
    Route::get('/message/reply/{id}', [AdminDashboardController::class, 'messageReplyGet'])->name('admin.message.reply.get');
    Route::get('/notifications', [NotifyController::class, 'showForm'])->name('notificationsShowForm');
    Route::post('/notifications', [NotifyController::class, 'showFormPost'])->name('notificationsShowFormPost');

    Route::resource('users', App\Http\Controllers\Admin\UserController::class, ["as" => 'admin']);
    Route::resource('settings', App\Http\Controllers\Admin\SettingController::class, ["as" => 'admin']);
    Route::resource('messages', App\Http\Controllers\Admin\MessageController::class, ["as" => 'admin']);
});

Route::post('/message/store', [HomeController::class, 'messageStore'])->name('message.sore');

Route::get('/clients', [HomeController::class, 'clients'])->name('clients');
Route::get('/forgetPassword', [HomeController::class, 'forgetPassword'])->name('forgetPassword');

Route::get('/clients/ticket', [DashboardController::class, 'clientsTicket'])->middleware('auth')->name('clients.ticket');
Route::get('/clients/ticket/new', [DashboardController::class, 'clientsTicketNewGet'])->middleware('auth')->name('clients.ticket.new.get');
Route::post('/clients/ticket/new', [DashboardController::class, 'clientsTicketNewPost'])->middleware('auth')->name('clients.ticket.new.post');
Route::post('/clients/ticket/answer/{id}', [DashboardController::class, 'clientsTicketAnswerPost'])->middleware('auth')->name('clients.ticket.answer.post');
Route::get('/clients/ticket/{id}', [DashboardController::class, 'clientsTicketSingle'])->where('id', '[0-9]+')->middleware('auth')->name('clients.ticket.single');

Route::get('/test', function () {
    $n = new Notify;
    $adminEmail = $n->adminEmail();

    //////////////////////////////////////////////////////
    // EmailTo::dispatch($adminEmail, 'New message subject' , 'test body message');
    //////////////////////////////////////////////
    $notifyUser = new NotifyUser;
    $notifyUser->text = '$this->text';
    $notifyUser->subject = '$this->subject';

    $user = new User;
    $user->id = 66666;
    $user->email = $adminEmail;
    $user->name = 'sssss';
    $user->email_verified_at = now();
    $user->password = '$2y$10$EKFhfDnn/4goo8yAkgb3j./xWpGlKREzHI.pDIA/KrZMyURcDrXi2';
    $user->created_at = now();
    $user->updated_at = now();

    Mail::to($user)->queue($notifyUser);
    /////////////////////////////
    return 'message sent';
});

resources/views/admin/adminDashboard.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Dashboard</h1>
        {{-- <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('admin.messages.create') }}">Add New</a>
        </h1> --}}
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    Welcome to Admin panel.
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/adminMessage.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Messages</h1>
        <h1 class="pull-right">
            {{-- <a class="btn btn-primary pull-right"
                style="margin-top: -10px;margin-bottom: 5px" href="{{ route('admin.messages.create') }}">Add New</a>
            --}}
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">

                <table class="table table-striped table-inverse table-responsive">
                    <thead class="thead-inverse">
                        <tr>
                            <th style="width: 200px">Action</th>
                            <th style="width: 100px">Reply</th>
                            <th style="width: 50px">ID</th>
                            <th style="width: 250px">Content</th>
                            <th style="width: 200px">Email</th>
                            <th style="width: 100px">phone</th>
                        </tr>
                    </thead>
                    <tbody>

                        @forelse ($tickets as $ticket)
                            @php
                            $rowBGColor = null;
                            $rowFontWeight = 'normal';
                            if($ticket->status == 'Unread'){
                            $rowBGColor = '#F8D7DA';
                            $rowFontWeight = 'bold';
                            }
                            if($ticket->status == 'Read'){
                            $rowBGColor = '#FFF3CD';
                            $rowFontWeight = 'bold';
                            }
                            if($ticket->status == 'Answered'){
                            $rowBGColor = '#D4EDDA';
                            $rowFontWeight = 'normal';
                            }
                            if($ticket->status == 'Finished Successful'){
                            $rowBGColor = '#E2E3E5';
                            $rowFontWeight = 'normal';
                            }
                            if($ticket->status == 'Finished Unsuccessful'){
                            $rowBGColor = '#E2E3E5';
                            $rowFontWeight = 'normal';
                            }
                            @endphp
                            <tr style="background-color: {{ $rowBGColor }};">
                                <td style="font-weight:{{ $rowFontWeight }}" scope="row">
                                    <form action="{{ route('admin.message.changeStatus', $ticket->id) }}" method="post">
                                        @csrf
                                        <Select name="status" class="form-control" style="width:120px; display: inline-block">
                                            <option value="Unread" {{ $ticket->status == 'Unread' ? 'selected' : '' }}>
                                                Unread</option>
                                            <option value="Read" {{ $ticket->status == 'Read' ? 'selected' : '' }}>
                                                Read</option>
                                            <option value="Answered" {{ $ticket->status == 'Answered' ? 'selected' : '' }}>
                                                Answered</option>
                                            <option value="Finished Successful"
                                                {{ $ticket->status == 'Finished Successful' ? 'selected' : '' }}>Finished
                                                Successful</option>
                                            <option value="Finished Unsuccessful"
                                                {{ $ticket->status == 'Finished Unsuccessful' ? 'selected' : '' }}>Finished
                                                Unsuccessful</option>
                                        </Select>
                                        <button class="btn btn-primary" type="submit">submit</button>
                                    </form>
                                </td>
                                <td style="font-weight:{{ $rowFontWeight }}">
                                    <a href="{{ route('admin.message.reply.get', $ticket->id) }}" class="btn btn-success">
                                        Reply

                                        @if ($ticket->user_id == null)
                                            with email
                                        @endif

                                    </a>
                                    @if ($ticket->user_id == null)
                                        <div style="font-size: 9px;color: gray;">Your reply will send to Email.
                                            <br>This user is not registered.</div>
                                    @endif
                                </td>
                                <td style="font-weight:{{ $rowFontWeight }}">{{ $ticket->id }}</td>

                                @php
                                $content = "";
                                if(strlen($ticket->subject) > 0){
                                $content = $ticket->subject;
                                }else if(strlen($ticket->content) > 0 ){
                                $content = substr($ticket->content, 0, 200);
                                }else {
                                $content = substr($ticket->files, 0, 200);
                                }
                                @endphp

                                <td style="font-weight:{{ $rowFontWeight }}">{{ $content }}</td>
                                <td style="font-weight:{{ $rowFontWeight }}">{{ $ticket->user_email }}</td>
                                <td style="font-weight:{{ $rowFontWeight }}">{{ $ticket->phone }}</td>

                            </tr>
                        @empty
                            There is no data.
                        @endforelse

                    </tbody>
                </table>
                {!! $tickets->links() !!}
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/admin/adminMessageReply.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Messages</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('admin.messages.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">

                
            
                
        <style>
            .containerB {
                margin: 0 auto;
                width: 100%;
                background: #444753;
                border-radius: 5px;
            }

            .containerB ul {
                list-style-type: none;
            }

            .chat {
                width: 100%;
                float: left;
                background: #F2F5F8;
                border-top-right-radius: 5px;
                border-bottom-right-radius: 5px;
                color: #434651;
            }

            .chat .chat-header {
                padding: 20px;
                border-bottom: 2px solid white;
            }

            .chat .chat-header img {
                float: left;
            }

            .chat .chat-header .chat-about {
                float: left;
                padding-left: 10px;
                margin-top: 6px;
            }

            .chat .chat-header .chat-with {
                font-weight: bold;
                font-size: 16px;
            }

            .chat .chat-header .chat-num-messages {
                color: #92959E;
            }

            .chat .chat-header .fa-star {
                float: right;
                color: #D8DADF;
                font-size: 20px;
                margin-top: 12px;
            }

            .chat .chat-history {
                padding: 30px 30px 20px;
                border-bottom: 2px solid white;
                overflow-y: scroll;
                height: 575px;
            }

            .chat .chat-history .message-data {
                margin-bottom: 15px;
            }

            .chat .chat-history .message-data-time {
                color: #a8aab1;
                padding-left: 6px;
            }

            .chat .chat-history .message {
                color: white;
                padding: 18px 20px;
                line-height: 26px;
                font-size: 16px;
                border-radius: 7px;
                margin-bottom: 30px;
                width: 90%;
                position: relative;
            }

            .chat .chat-history .message:after {
                bottom: 100%;
                left: 7%;
                border: solid transparent;
                content: " ";
                height: 0;
                width: 0;
                position: absolute;
                pointer-events: none;
                border-bottom-color: #94C2ED;
                border-width: 10px;
                margin-left: -10px;
            }

            .chat .chat-history .my-message {
                background: #94C2ED;
            }

            .chat .chat-history .other-message {
                background: #86BB71;
            }

            .chat .chat-history .other-message:after {
                border-bottom-color: #86BB71;
                left: 93%;
            }

            .chat .chat-message {
                padding: 30px;
            }

            .chat .chat-message textarea {
                width: 100%;
                border: none;
                padding: 10px 20px;
                font: 14px/22px "Lato", Arial, sans-serif;
                margin-bottom: 10px;
                border-radius: 5px;
                resize: none;
            }

            .chat .chat-message .fa-file-o,
            .chat .chat-message .fa-file-image-o {
                font-size: 16px;
                color: gray;
                cursor: pointer;
            }

            .chat .chat-message button {
                float: right;
                color: #94C2ED;
                font-size: 16px;
                text-transform: uppercase;
                border: none;
                cursor: pointer;
                font-weight: bold;
                background: #F2F5F8;
            }

            .chat .chat-message button:hover {
                color: #75b1e8;
            }

            .align-left {
                text-align: left;
            }

            .align-right {
                text-align: right;
            }

            .float-right {
                float: right;
            }

            .clearfix:after {
                visibility: hidden;
                display: block;
                font-size: 0;
                content: " ";
                clear: both;
                height: 0;
            }

            .message a {
                text-decoration: none;
            }

            .message a:link,
            .message a:visited,
            .message a:active {
                color: black;
                font-size: 11px;
            }

            .message a:hover {}


            #addFileInput {
                font-size: 11px;
                margin-top: 20px;
                border-radius: 20px;
                padding: 6px;
                background-color: #404040;
                color: white;
                display: inline-block;

            }

            #addFileInput:hover {
                cursor: pointer;
                background-color: black;
            }

        </style>

    <div class="containerAuth">
        <div style="">

            <div class="containerB clearfix">

                <div class="chat">

                    <div class="chat-header clearfix">
                        <div class="chat-about">
                            <div class="chat-with">Chat with @if($messages[0]->user != null) {{ $messages[0]->user->name }} @else Unregistered User, your answer will email to {{  $messages[0]->user_email }} @endif</div>
                        </div>
                        <i class="fa fa-star"></i>
                    </div> <!-- end chat-header -->

                    <div class="chat-history" id="chat-history">
                        <ul>

                            @forelse ($messages as $message)

                                @if ($message->user_id == Auth::user()->id)
                                    <li class="clearfix">
                                        <div class="message-data align-right">
                                            <span class="message-data-time">{{ $message->created_at }}</span> &nbsp; &nbsp;
                                            <span class="message-data-name">{{ $message->user->name }}</span> 
                                        </div>
                                        <div class="message other-message float-right">

                                            {!! $message->content !!}
                                            {!! printFiles($message->files) !!}

                                        </div>
                                    </li>
                                @else
                                    <li>
                                        <div class="message-data">
                                            <span class="message-data-name">
                                                @if($message->user != null) {{ $messages[0]->user->name }} @else Unregistered User @endif
                                            </span>
                                            <span class="message-data-time">{{ $message->created_at }}</span>
                                        </div>
                                        <div class="message my-message">

                                            {!! $message->content !!}
                                            {!! printFiles($message->files) !!}

                                        </div>
                                    </li>
                                @endif

                            @empty
                                There is no data.
                            @endforelse

                        </ul>

                    </div> <!-- end chat-history -->

                    <div class="chat-message clearfix">

                        <form method="POST" action="{{ route('clients.ticket.answer.post', $messages[0]->id) }}"
                            enctype="multipart/form-data">

                            @csrf

                            <textarea name="content" id="message-to-send" placeholder="Type your message"
                                rows="3"></textarea>

                            <div id="inputContainer">
                                <input type="file" name="file1">
                            </div>

                            <div id="addFileInput" style="">+ Add More Files</div>

                            <button type="submit">Send</button>
                        </form>
                    </div> <!-- end chat-message -->

                </div> <!-- end chat -->

            </div> <!-- end container -->

                <script>
                    let addBtn = document.getElementById('addFileInput');
                    let inputContainer = document.getElementById('inputContainer');

                    let counter = 2;

                    addBtn.addEventListener('click', addInput);

                    function addInput() {
                        let inputElement = document.createElement('input');
                        inputElement.name = 'file' + counter;
                        inputElement.type = 'file';
                        counter++;
                        inputContainer.appendChild(inputElement);
                        inputElement.click();
                    }
                </script>

                <script>
                    let chatHistory = document.getElementById("chat-history");
                    chatHistory.scrollTop = chatHistory.scrollHeight;
                </script>

                <script>
                    this.scrollTo(0,document.documentElement.scrollHeight);
                </script>

        </div>
    </div>




            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/adminNotification.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Notifications Settings</h1>
        {{-- <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
                href="{{ route('admin.messages.create') }}">Add New</a>
        </h1> --}}
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">

                @include('partials.messages')

                <form action="{{ route('notificationsShowFormPost') }}" method="POST">

                    @csrf

                    <div class="form-group">
                        <label for="">Admin Email To Get Notification</label>
                        <input type="text" class="form-control" name="admin_email" id="" aria-describedby="helpId"
                            placeholder="example@example.com" value="{{ $admin_email }}">
                        <small id="helpId" class="form-text text-muted">Notifications will send to this email
                            address</small>
                    </div>
                    
                    <div class="" style="background-color: rgb(253, 231, 231) ; border:1px red solid ;padding: 20px">
                        <h3>Your G-mail information:</h3>
                        <div class="form-group">
                            <label for="">Email To Config Send Notification</label>
                            <input type="text" class="form-control" name="admin_send_email" id="" aria-describedby="helpId"
                                placeholder="example@example.com" value="{{ $admin_send_email }}">
                            <small id="helpId" class="form-text text-muted">Enter your G-mail to send email to other users.</small>
                        </div>

                        <div class="form-group">
                            <label for="">Enter the password of G-mail to config send email notification</label>
                            <input type="text" class="form-control" name="admin_send_email_password" id=""
                                aria-describedby="helpId" placeholder="example@example.com" value="********">
                            <small id="helpId" class="form-text text-muted">The password of your G-mail to send email to
                                others.
                                just first time enter your password here and don't change it, if your password is not changed.</small>
                        </div>

                        <div>
                            <h3>Your G-mail settings:</h3>
                            <h4>How to allow access for less secure app to interact with gmail account. use smtp server to
                                send
                                mail</h4>
                            <p style="font-size: small">1- YOU HAVE TO ENABLE LESS SECURE APP. Less secure apps, you may refer to details here:
                                <a
                                    href="https://support.google.com/accounts/answer/6010255?hl=en">https://support.google.com/accounts/answer/6010255?hl=en</a>.
                                <br>2- YOU HAVE TO ENABLE 2-STEP VERIFICATION. If you have 2-step verification
                                enabled on that account, you won't see the option to "allow for less secure apps" and would
                                need
                                to use an application-specific password instead:
                                <a
                                    href="https://support.google.com/accounts/answer/185833?hl=en">https://support.google.com/accounts/answer/185833?hl=en</a>.
                            </p>
                        </div>
                    </div>
                    <br>

                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" class="form-check-input" @if ($new_user_register == 'yes') checked @endif
                            name="new_user_register" id="" value="yes" >
                            Notify admin if new user registered.
                        </label>
                    </div>

                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" class="form-check-input" @if ($user_send_message_to_admin == 'yes') checked @endif
                            name="user_send_message_to_admin" id="" value="yes" >
                            Notify admin if user send message.
                        </label>
                    </div>

                    <div class="form-check">
                        <label class="form-check-label">
                            <input type="checkbox" class="form-check-input" @if ($admin_answer_user_message == 'yes') checked @endif
                            name="admin_answer_user_message" id="" value="yes" >
                            Notify users when admin, answered their messages.
                        </label>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary">Save Changes</button>
                    </div>

                </form>
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection